ci: print-debug due to GH actions lack of local execution

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -25,6 +25,15 @@ jobs:
           key: ${{ runner.os }}-poetry-3.12-${{ hashFiles('**/poetry.lock') }}
       - name: Install dev dependencies
         run: bash ./scripts/ci/github/install_dev_dependencies.sh
+      - name: debug
+        run: |
+          set -x
+          echo "$PATH" | tr ':' '\n'
+          command -v python
+          command -v python3
+          command -v poetry || echo "missing poetry"
+          stat .venv/bin/python
+          .venv/bin/python --version
       - name: Python lints
         run: bash ./scripts/ci/python_lints.sh
         # TODO: figure out how to cache the .mypy_cache
@@ -33,9 +42,13 @@ jobs:
       - name: scrape upstream version
         run: bash ./scripts/ci/github/scrape_upstream_version.sh
       - name: package binaries
-        run: python3 -m scripts.build.all # should take ~30s
+        run: |
+          export PATH="$PWD/.venv/bin:$PATH"
+          python3 -m scripts.build.all # should take ~30s
       - name: package python api
-        run: python3 -m scripts.build.api_package
+        run: |
+          export PATH="$PWD/.venv/bin:$PATH"
+          python3 -m scripts.build.api_package
       - name: Archive dist
         uses: actions/upload-artifact@v4
         with:
